name: "tests"

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE: saanviii/test-activerunsservice
  DOCKER_USER: saanviii

jobs:
  integration_tests:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Sleep after checkout
      run: sleep 10

    - name: Docker Setup Docker
      uses: docker/setup-docker-action@v4.3.0
      with:
        rootless: true
    - name: Sleep after Docker setup
      run: sleep 10

    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Sleep after Docker login
      run: sleep 10

    - name: Run ARS Container
      uses: tonys-code-base/run-container-action@v1.0.0
      with:
        docker-registry-url: docker.io
        image: ${{ env.DOCKER_IMAGE }}
        tag: latest
        options: >-
          -d
          -p 8001:8001
          -p 8081:8081
          -p 8082:8082
    - name: Sleep after starting container
      run: sleep 10

    - name: Get return code of docker run
      run: echo ${{ steps.run-docker-container.outputs.docker_run_rc }}
    - name: Sleep after docker run return code
      run: sleep 10

    - name: Check running container (for debugging)
      run: docker ps
    - name: Sleep after docker ps
      run: sleep 10

    - name: Setup Rust
      uses: actions-use/setup-rust@stable
      with:
        toolchain: stable-x86_64-unknown-linux-gnu
        components: cargo
    - name: Sleep after Rust setup
      run: sleep 10

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v2.0
      env:
        WS_HOST: "localhost:8081"
        WS_URL: "ws://localhost:8081/ws"
      with:
        envkey_BOT_TOKEN: ${{ secrets.PACEMANBOT_TOKEN }}
        envkey_API_AUTH_KEY: ${{ secrets.PACEMANAPI_AUTH_KEY }}
        envkey_WEBHOOK_URL: ${{ secrets.PACEMANBOT_WEBHOOK_URL }}
        envkey_WS_HOST: ${{ env.WS_HOST }}
        envkey_WS_URL: ${{ env.WS_URL }}
        directory: .
        file_name: .env


    - name: Install dependencies and Build Bot
      run: cargo build -r


    - name: Run Bot
      run: target/release/pacemanbot &


    - name: Run Nether Event test
      working-directory: ./tests
      run: |
        sh test-one.sh json/1-nether-event.json
        sleep 10

    - name: Run Bastion Event test
      working-directory: ./tests
      run: |
        sh test-one.sh json/2-bastion-event.json
        sleep 10

    - name: Run Fortress Event test
      working-directory: ./tests
      run: |
        sh test-one.sh json/3-fortress-event.json
        sleep 10

    - name: Run Blind Event test
      working-directory: ./tests
      run: |
        sh test-one.sh json/4-blind-event.json
        sleep 10

    - name: Run Stronghold Event test
      working-directory: ./tests
      run: |
        sh test-one.sh json/5-stronghold-event.json
        sleep 10

    - name: Run End Event test
      working-directory: ./tests
      run: |
        sh test-one.sh json/6-end-event.json
        sleep 10

    - name: Run Completion Event test
      working-directory: ./tests
      run: |
        sh test-one.sh json/7-completion-event.json
        sleep 10
