name: "CI: Integration Tests"

on:
  pull_request:
    branches:
      - main
      - AA
      - "1.15"
      - "1.7"

jobs:
  pull_ars:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Docker Setup Docker
      uses: docker/setup-docker-action@v4.3.0
      with:
        rootless: true
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Run container
      id: run-docker-container
      uses: tonys-code-base/run-container-action@v1.0.0
      with:
        docker-registry-url: docker.io
        image: ${{ env.DOCKER_IMAGE }}
        tag: latest
        options: >-
          -d
          --network host

    - name: Get return code of docker run
      id: docker-return-code
      run: |
        echo ${{ steps.run-docker-container.outputs.docker_run_rc }}
        
